### ISSUE TITLE
Gameboy/ Color Support

### ISSUE THREAD

**Issue by MaxLempira** [FIX94/gba-link-cable-dumper#4]
Possibility to dump GB/C Game, Save & BIOS

**Comment by MaxLempira** [comment]
Forgot! Thanks for this awesome tool, but I'm very worried'bout GBC Games (PKMN), so many hours inverted on these hehe, hope this can be possible!

And again, thanks!

**Comment by FIX94** [comment]
this is technically not doable sadly, as soon as you insert a gb game into a gba via a hardware switch it'll restart into gb mode and also change the voltage given to the cart so it can actually be read so even if you were to remove that hardware switch you couldnt read it anyways because of the voltage differences and because of actually no interface available to read them (its exclusive to gba reading).

**Comment by GB-CG** [comment]
@MaxLempira There's the Gameboy-_(snip!)_

Actually, scratch that, the GB64 program on Everdrive 64 does a better job.

**Comment by MaxLempira** [comment]
Those are sad news, I though finally I would be able to Backup my saves, but thanks anyway.

@GB-CG I wanted to get one time ago, but then I found that I won't be able to Backup those saves to my PC, something that now (VC PKMN Games) I want more. Maybe using Transfer Pack and N64 Controller to USB can do the work... I'll search for something... Thanks for the info.

I'll close the Issue then ;)

**Comment by vgmoose** [comment]
Does this project make this any closer to being possible?

https://github.com/AntonioND/gba-switch-to-gbc
